### ISSUE TITLE
Is "RARC" just "Refactored Archive"?

### ISSUE THREAD

**Issue by LordNed** [LordNed/WArchive-Tools#5]
Based on other changes in Wind Waker (CAMR -> RCAM, PATH -> RPAT) and a few in Twilight Princess, it seems that Nintendo has the habit of sticking an "R" on the front for a similar/new version of the format. Perhaps this stands for Refactored?

If so, can we stop calling them "RARC" and just call them "Archive"?

**Comment by Sage-of-Mirrors** [comment]
...That's actually a very, very good observation. If that's the case, then it seems like the original archive format was discarded before even Luigi's Mansion, a GC launch title, which uses the RARC format compressed with Yay0 (which, by the way, I believe is the compression type applied to the GC's BIOS. Don't quote me on that though). I'm all for dropping RARC in favor of calling both .arc and .rarc "archives." .arc files are just .rarc files, in fact. It's just that Nintendo decided to call them .arc rather than .rarc. That's another clue that RARC just means "Refactored ARChive."

**Comment by LordNed** [comment]
Code has been renamed to reflect this decision.
